export const ERROR_TYPES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  MISSING_DATA: 'MISSING_DATA',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  USER_EXISTS: 'USER_EXISTS',
  NATIVE_ERROR: 'NATIVE_ERROR',
  INVALID_TRANSACTION_TYPE: 'INVALID_TRANSACTION_TYPE',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  BAD_GUY_ERROR: 'BAD_GUY_ERROR',
};
